-- Migration: Baseline migration
-- Purpose: Represents the existing DB schema at project start
-- Generated by: Prisma introspect + manual setup

-- ============================================================
-- Existing tables (created separately, not managed by Prisma)
-- These are kept as reference for migration history
-- ============================================================

-- Users table (existing)
CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR(50) UNIQUE NOT NULL,
    "password_hash" TEXT NOT NULL,
    "email" VARCHAR(100) UNIQUE NOT NULL,
    "dni" VARCHAR(20) UNIQUE NOT NULL,
    "user_type" VARCHAR(20) DEFAULT 'cliente' NOT NULL,
    "is_active" BOOLEAN DEFAULT true NOT NULL,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6)
);

-- Indexes on users
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users"("email");
CREATE INDEX IF NOT EXISTS "idx_users_username" ON "users"("username");

-- Vendedores table (existing - will be deprecated after migration)
CREATE TABLE IF NOT EXISTS "vendedores" (
    "vendedor_id" SERIAL PRIMARY KEY,
    "nombres" VARCHAR(100) NOT NULL,
    "apellidos" VARCHAR(100) NOT NULL,
    "correo" VARCHAR(150) UNIQUE NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "dni" VARCHAR(20) UNIQUE NOT NULL,
    "konami_id" VARCHAR(50) UNIQUE,
    "whatsapp" VARCHAR(20),
    "instagram" VARCHAR(100),
    "facebook" VARCHAR(150),
    "otro" VARCHAR(255),
    "ultimo_login" TIMESTAMP(6),
    "intentos_fallidos" INT DEFAULT 0,
    "bloqueado_hasta" TIMESTAMP(6),
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "activo" BOOLEAN DEFAULT true,
    "email_verificado" BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS "idx_vendedores_activo" ON "vendedores"("activo");
CREATE INDEX IF NOT EXISTS "idx_vendedores_correo" ON "vendedores"("correo");
CREATE INDEX IF NOT EXISTS "idx_vendedores_dni" ON "vendedores"("dni");
CREATE INDEX IF NOT EXISTS "idx_vendedores_konami_id" ON "vendedores"("konami_id");

-- Cards table (existing - main catalog)
CREATE TABLE IF NOT EXISTS "cards" (
    "id" BIGSERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "type" VARCHAR(100),
    "human_readable_card_type" VARCHAR(100),
    "frame_type" VARCHAR(50),
    "description" TEXT,
    "race" VARCHAR(100),
    "atk" INT,
    "def" INT,
    "level" INT,
    "attribute" VARCHAR(50),
    "archetype" VARCHAR(100),
    "ygoprodeck_url" TEXT
);

CREATE INDEX IF NOT EXISTS "idx_cards_archetype" ON "cards"("archetype");
CREATE INDEX IF NOT EXISTS "idx_cards_name" ON "cards"("name");

-- Card images (existing)
CREATE TABLE IF NOT EXISTS "card_images" (
    "card_id" BIGINT,
    "image_url" TEXT,
    "image_url_small" TEXT,
    "image_url_cropped" TEXT,
    "image_id" SERIAL PRIMARY KEY
);

CREATE INDEX IF NOT EXISTS "idx_card_images_card_id" ON "card_images"("card_id");

-- Card prices (existing)
CREATE TABLE IF NOT EXISTS "card_prices" (
    "id" SERIAL PRIMARY KEY,
    "card_id" BIGINT,
    "cardmarket_price" DECIMAL(10,2),
    "tcgplayer_price" DECIMAL(10,2),
    "ebay_price" DECIMAL(10,2),
    "amazon_price" DECIMAL(10,2),
    "coolstuffinc_price" DECIMAL(10,2),
    "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_card_prices_card_id" ON "card_prices"("card_id");

-- Card sets (existing)
CREATE TABLE IF NOT EXISTS "card_sets" (
    "id" SERIAL PRIMARY KEY,
    "card_id" BIGINT,
    "set_name" VARCHAR(255) NOT NULL,
    "set_code" VARCHAR(50),
    "set_rarity" VARCHAR(100),
    "set_rarity_code" VARCHAR(20),
    "set_price" DECIMAL(10,2)
);

CREATE INDEX IF NOT EXISTS "idx_card_sets_card_id" ON "card_sets"("card_id");

-- Card printings (existing)
CREATE TABLE IF NOT EXISTS "card_printings" (
    "printing_id" SERIAL PRIMARY KEY,
    "card_id" BIGINT NOT NULL,
    "set_name" VARCHAR(255) NOT NULL,
    "set_code" VARCHAR(50) NOT NULL,
    "set_rarity" VARCHAR(100),
    "set_rarity_code" VARCHAR(50),
    "set_price" DECIMAL(10,2) DEFAULT 0.00
);

-- Card typelines (existing)
CREATE TABLE IF NOT EXISTS "card_typelines" (
    "id" SERIAL PRIMARY KEY,
    "card_id" BIGINT,
    "typeline" VARCHAR(100) NOT NULL
);

-- Card types (existing)
CREATE TABLE IF NOT EXISTS "card_types" (
    "card_id" BIGINT NOT NULL,
    "type_name" VARCHAR(50) NOT NULL,
    PRIMARY KEY ("card_id", "type_name")
);

-- Banlist info (existing)
CREATE TABLE IF NOT EXISTS "banlist_info" (
    "card_id" BIGINT PRIMARY KEY,
    "ban_ocg" VARCHAR(50)
);

-- Card banlist (existing)
CREATE TABLE IF NOT EXISTS "card_banlist" (
    "id" SERIAL PRIMARY KEY,
    "card_id" BIGINT,
    "ban_tcg" VARCHAR(50),
    "ban_ocg" VARCHAR(50),
    "ban_goat" VARCHAR(50)
);

-- User roles (existing)
CREATE TABLE IF NOT EXISTS "user_roles" (
    "id" SERIAL PRIMARY KEY,
    "user_id" INT NOT NULL,
    "role" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE("user_id", "role")
);

CREATE INDEX IF NOT EXISTS "idx_user_roles_user_id" ON "user_roles"("user_id");

-- Inventario (existing - connected to vendedores, NOT users)
CREATE TABLE IF NOT EXISTS "inventario" (
    "inventario_id" SERIAL PRIMARY KEY,
    "vendedor_id" INT NOT NULL,
    "card_id" BIGINT NOT NULL,
    "cantidad" INT DEFAULT 1 NOT NULL,
    "precio" DECIMAL(10,2),
    "condicion" VARCHAR(50) DEFAULT 'Near Mint',
    "idioma" VARCHAR(20) DEFAULT 'Inglés',
    "edicion" VARCHAR(20),
    "notas" TEXT,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_inventario_precio" ON "inventario"("precio");

-- Cart (existing)
CREATE TABLE IF NOT EXISTS "cart" (
    "id" SERIAL PRIMARY KEY,
    "user_id" INT UNIQUE NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Cart items (existing)
CREATE TABLE IF NOT EXISTS "cart_items" (
    "id" SERIAL PRIMARY KEY,
    "cart_id" INT NOT NULL,
    "product_id" INT NOT NULL,
    "cantidad" INT NOT NULL,
    "added_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UNIQUE("cart_id", "product_id")
);

-- Orders (existing)
CREATE TABLE IF NOT EXISTS "orders" (
    "id" SERIAL PRIMARY KEY,
    "user_id" INT NOT NULL,
    "status" TEXT DEFAULT 'pendiente' NOT NULL,
    "pickup_code" CHAR(6) UNIQUE NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_orders_pickup_code" ON "orders"("pickup_code");
CREATE INDEX IF NOT EXISTS "idx_orders_user_id" ON "orders"("user_id");

-- Order items (existing)
CREATE TABLE IF NOT EXISTS "order_items" (
    "id" SERIAL PRIMARY KEY,
    "order_id" INT NOT NULL,
    "product_id" INT NOT NULL,
    "card_name" TEXT NOT NULL,
    "precio_snapshot" DECIMAL(10,2) NOT NULL,
    "cantidad" INT NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_order_items_product_id" ON "order_items"("product_id");

-- Store products (existing)
CREATE TABLE IF NOT EXISTS "store_products" (
    "id" SERIAL PRIMARY KEY,
    "card_id" BIGINT UNIQUE NOT NULL,
    "precio" DECIMAL(10,2) NOT NULL,
    "stock" INT DEFAULT 0 NOT NULL,
    "activo" BOOLEAN DEFAULT true NOT NULL,
    "created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_store_products_activo" ON "store_products"("activo");